# version: "3.8"
# services:
#   mariadb:
#     container_name: mariadb			# Le nom du container
#     networks:
#       - inception            			
#     build: 
#       context: requirements/mariadb 	# ou se trouve son Dockerfile
#       dockerfile: Dockerfile			
#     env_file: .env                  
#     volumes:                        
#       - mariadb:/var/lib/mysql
#     restart: unless-stopped         # redémarre tant qu'il n'est pas stoppé 
#     expose:                         
#       - "3306"
#   nginx:
#     container_name: nginx
#     volumes:
#       - wordpress:/var/www/wordpress
#     networks:
#       - inception
#     depends_on:        			 # Nouvelle ligne, indiquant de ne pas démarrer NGINX tant que WordPress n'a pas démarré.
#       - wordpress
#     build: 
#       context: requirements/nginx
#       dockerfile: Dockerfile
#     env_file: .env
#     ports:
#       - "443:443" 		# on indique le port qui sera exposé a la machine locale
#     restart: on-failure 		# le container redémarrera uniquement en cas de crash.
#   wordpress:
#     container_name: wordpress
#     env_file: .env
#     volumes:
#       - wordpress:/var/www/wordpress
#     networks:
#       - inception
#     build: 
#       context: requirements/wordpress
#       dockerfile: Dockerfile
#     depends_on:    					# WordPress démarrera uniquement après MariaDB (sinon il ne pourra pas configurer la base de données...)
#       - mariadb
#     restart: on-failure
#     expose: 
#       - "9000"				
# volumes:
#   wordpress:
#     driver: local # ici nous stockons le volume en local
#     driver_opts:
#       type: 'none' 									# aucun type spécifique
#       o: 'bind'
#       device: '/home/student/data/wordpress' #Ou stocker le dossier sur votre ordinateur en local
#   mariadb:
#     driver: local
#     driver_opts:
#       type: 'none' 
#       o: 'bind'										 # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
#       device: '/home/student/data/mariadb' #Ou stocker le dossier sur votre ordinateur en local
# networks:
#     inception:
#       driver: bridge



services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    networks: [inception]
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    depends_on: [mariadb]
    volumes:
      - wordpress_data:/var/www/html
    expose:
      - "9000"
    networks: [inception]
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    depends_on: [wordpress]     # start after PHP-FPM is ready
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks: [inception]
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/mariadb"

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/wordpress"

networks:
  inception:
    driver: bridge
