version: "3.8"

networks:
  inception:
    driver: bridge            # 42 subject: only the default bridge is allowed

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb      # host path
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - type: bind
        source: /home/${USER}/data/mariadb
        target: /var/lib/mysql
      - ./requirements/mariadb/conf/init.sql:/docker-entrypoint-initdb.d/99-init.sql:ro
    expose:
      - "3306"
    networks:
      - inception
    restart: unless-stopped
    healthcheck:                              # let WordPress wait until DB is ready
      test: ["CMD-SHELL", "mysqladmin --protocol=socket ping -u root --silent"]
      interval: 5s
      retries: 5

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    expose:
      - "9000"
    environment:               # auto_config.sh expects these
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_MAIL: ${WP_ADMIN_MAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - inception
    restart: unless-stopped

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      inception:
        aliases:
          - wordpress
    restart: unless-stopped
