CREATE DATABASE IF NOT EXISTS wordpress
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'sinawara'@'%' IDENTIFIED BY 'inception';
GRANT ALL PRIVILEGES ON wordpress.* TO 'sinawara'@'%';

FLUSH PRIVILEGES;